//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        public int IdPelicula { get; set; }
        public string Nombre { get; set; }
        public string Director { get; set; }
        public string Elenco { get; set; }
        public string Genero { get; set; }
        public string Sinopsis { get; set; }
        public byte[] Foto { get; set; }
        public string Trailers { get; set; }
    }
}
